sovity/edc-ui

- .github/workflows/build-and-release-image.yaml
- CHANGELOG.md
- README.md
- src/modules/app/config/app-config-properties.ts
- closes #7 
- added some documentation to README.md
> fix release image name

- .github/workflows/build-and-release-image.yaml
- src/modules/app/components/navigation/navigation.component.html
- src/modules/app/config/app-config.ts
- src/modules/app/config/edc-ui-profile-config.ts
- src/modules/app/config/edc-ui-profile.ts
closes https://github.com/sovity/edc-ui/issues/29
before 
after
> 29 fix logo paddings

- CHANGELOG.md
- src/modules/app/components/navigation/navigation.component.html
- src/modules/app/components/navigation/navigation.component.scss
- src/styles.scss
Solves the issue of nav-bar getting hidden behind the feedback widget
Tested with mock backend
> fix:hidden menu under feedback widget

- src/modules/app/config/edc-ui-profile.ts
> fix mds logo not showing

- README.md
- docs/getting-started/docker-compose.yaml
> chore add getting-started section

- .gitattributes
- dependabot.yml
- package-lock.json
- package.json
> 48 chore bump dependencies

- README.md
> fix contact email typo in README.md

- CHANGELOG.md
> chore update CHANGELOG.md

- CHANGELOG.md
- docs/getting-started/docker-compose.yaml
- src/modules/edc-dmgmt-client/api/contractAgreement.service.ts
> fix contract agreement transfer ext api endpoint

- docs/getting-started/docker-compose.yaml
- src/modules/edc-demo/components/language-select/language-select-item.service.ts
- fixes docker-compose.yaml
- fixes default language select item
> Fix getting started and default language select item

- CHANGELOG.md
- fake-backend/json/transferProcess.json
- src/modules/edc-demo/components/dashboard-donut-chart/dashboard-donut-chart.component.html
- src/modules/edc-demo/components/dashboard-donut-chart/donut-chart-data.ts
- src/modules/edc-demo/components/dashboard/dashboard-data.service.ts
- src/modules/edc-demo/components/dashboard/dashboard-data.ts
- src/modules/edc-demo/components/dashboard/dashboard.component.html
- src/modules/edc-demo/services/contract-negotiation.service.ts
- src/modules/edc-demo/services/transfer-process-utils.ts
> fix dashboard mixing incoming and outgoing transfer processes

- CHANGELOG.md
- src/modules/app/app.module.ts
- src/modules/edc-demo/components/asset-editor-dialog/asset-editor-dialog-form-model.ts
- src/modules/edc-demo/components/asset-editor-dialog/asset-editor-dialog-form.ts
- src/modules/edc-demo/components/asset-editor-dialog/asset-editor-dialog.component.html
- src/modules/edc-demo/components/asset-editor-dialog/asset-editor-dialog.component.ts
- src/modules/edc-demo/components/asset-editor-dialog/data-address-type.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-advanced-form-builder.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-advanced-form-model.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-datasource-form-builder.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-datasource-form-model.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-metadata-form-builder.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/asset-metadata-form-model.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/http-datasource-auth-header-type.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/http-datasource-form-mapper.ts
- src/modules/edc-demo/components/asset-editor-dialog/model/http-datasource-header-form-model.ts
- src/modules/edc-demo/components/new-policy-dialog/new-policy-dialog-form.ts
- src/modules/edc-demo/models/http-datasource-properties.ts
- src/modules/edc-demo/services/asset-entry-builder.ts
- src/modules/edc-demo/services/asset-property-mapper.ts
- src/modules/edc-demo/services/policy-definition-builder.ts
- src/modules/edc-demo/utils/form-group-utils.ts
- src/modules/edc-demo/utils/record-utils.ts
- src/styles.scss
> feat share any REST endpoint

- CHANGELOG.md
removed empty sections from copy-pasting in changelog
added overview message for latest release
> 2023 02 20 changelog cleanup

- .github/workflows/automerge.yml
Adds continue-on-error in step level of automerge action. This will possibly fix https://github.com/sovity/edc-ui/issues/136
> chore: add continue on error in step level

- CHANGELOG.md
- README.md
> fix compatibility information in README.md

- src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
This PR adds small changes to error handling in the UI. Especially for the case of infrastructure failures. 
Fixes https://github.com/sovity/edc-extensions/issues/105
> chore: improve error handling for contract definition dialog

- src/modules/edc-demo/components/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog-form-model.ts
- src/modules/edc-demo/components/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog-form.ts
- src/modules/edc-demo/components/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.html
- src/modules/edc-demo/services/http-params-mapper.service.ts
fixes transfer dialog button text
removes transfer dialog payload
no changelog entry required due to fixing an unreleased feature
> fix payload configurable in data sink

- src/modules/app/app-routing.module.ts
This PR rearranges the order of items in the sidebar.
> chore: change order of sidebar

- CHANGELOG.md
- add section for next release
- added some missing details to CHANGELOG.md
> chore prepare CHANGELOG.md for release

- src/modules/edc-demo/components/asset-viewer/asset-viewer.component.ts
- src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
- src/modules/edc-demo/components/contract-definition-page/contract-definition-page.service.ts
- src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts
- src/modules/edc-demo/components/dashboard/dashboard-data.service.ts
- src/modules/edc-demo/components/policy-view/policy-view.component.ts
- src/modules/edc-demo/components/transfer-history/transfer-history-viewer.component.ts
- src/modules/edc-demo/services/asset-service-mapped.ts
- src/modules/edc-demo/services/contract-offer.service.ts
closes https://github.com/sovity/edc-ui/issues/204
when migrating to MS9 we should switch to dedicated UI APIs solving issues like these
> fix queries containing implicit limit of 50

- CHANGELOG.md
- src/modules/app/app.component.ts
- src/modules/edc-demo/services/login-polling.service.ts
closes https://github.com/sovity/PMO-Software/issues/148
> feat polling to keep session alive

- src/modules/edc-demo/components/contract-agreement-page/contract-agreement-page.component.html
- src/modules/edc-demo/components/contract-agreement-page/contract-agreement-page.data.ts
- src/modules/edc-demo/components/contract-agreement-page/contract-agreement-page.service.ts
- src/modules/edc-demo/components/horizontal-section-divider/horizontal-section-divider.component.html
- src/modules/edc-demo/components/horizontal-section-divider/horizontal-section-divider.component.ts
- src/modules/edc-demo/edc-demo.module.ts
- src/styles.scss
closes https://github.com/sovity/edc-ui/issues/254
When consuming + providing
When only consuming
When only providing
When none
> feat separate contract agreements

- CHANGELOG.md
- fake-backend/json/contractDefinitions.json
- src/modules/edc-demo/components/contract-definition-cards/contract-definition-card-builder.ts
closes https://github.com/sovity/edc-ui/issues/243
> fix contract definition page failing for all operators but IN

- CHANGELOG.md
- src/app/app.component.ts
> fix changelog and build

- CHANGELOG.md
- src/app/core/services/title-utils.service.ts
- src/app/routes/broker-ui/broker-ui.component.html
- src/app/routes/broker-ui/broker-ui.component.scss
- src/app/routes/broker-ui/broker-ui.component.ts
closes https://github.com/sovity/edc-broker-server-extension/issues/5
> feat: copyright footer (broker)

- fake-backend/json/assets.json
- fake-backend/serve.js
- package-lock.json
- package.json
- src/app/component-library/catalog/asset-detail-dialog/asset-detail-dialog.component.ts
- src/app/core/services/api/edc-api.service.ts
- src/app/core/services/asset-entry-builder.ts
- src/app/core/services/asset-service-mapped.ts
- src/app/core/services/data-address-mapper.ts
- src/app/core/services/http-params-mapper.service.ts
- src/app/core/services/login-polling.service.ts
- src/app/routes/connector-ui/asset-page/asset-create-dialog/asset-create-dialog.component.ts
- src/app/routes/connector-ui/asset-page/asset-page/asset-page.component.ts
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.ts
- src/app/routes/connector-ui/contract-definition-page/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
- src/app/routes/connector-ui/dashboard-page/dashboard-page/dashboard-page-data.service.ts
closes https://github.com/sovity/edc-ui/issues/392
closes https://github.com/sovity/edc-ui/issues/397
closes https://github.com/sovity/edc-ui/issues/421
> 392 use new create asset endpoint in UI

- CHANGELOG.md
- src/app/routes/broker-ui/catalog-page/catalog-page/catalog-page.component.ts
- src/app/routes/broker-ui/legal-notice-page/legal-notice-page/legal-notice-page.component.html
closes https://github.com/sovity/edc-broker-server-extension/issues/239
closes https://github.com/sovity/edc-broker-server-extension/issues/241
> Bugfixes for MDS 1.2

- src/app/core/services/http-params-mapper.service.ts
- src/app/core/services/models/data-address-properties.ts
- src/app/routes/connector-ui/asset-page/asset-create-dialog/asset-create-dialog.component.html
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.html
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.ts
- overriding of data offer + counterparty connector information will be done in the backend
> fix: custom data address for EDC 0

- CHANGELOG.md
- src/app/core/config/app-config-properties.ts
- src/app/core/config/app-config.builder.ts
- src/app/core/config/app-config.ts
- src/app/core/config/profiles/edc-ui-feature.ts
- src/app/core/config/profiles/edc-ui-profile-data.ts
- src/app/routes/connector-ui/dashboard-page/dashboard-page/dashboard-page.component.html
- src/app/routes/connector-ui/dashboard-page/dashboard-page/dashboard-page.component.ts
Add sovity info box to dashboard
> feat: add sovity box to dashboard

- src/app/core/config/profiles/edc-ui-profile-data.ts
- src/app/routes/connector-ui/connector-ui.component.html
component
Add powered by Sovity section to the sidebar
> Add powered by Sovity section to the sidebar

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/core/services/api/fake-backend/broker-fake-impl/connector-fake-impl.ts
- src/app/routes/broker-ui/connector-page/connector-cards/connector-cards.component.html
> feat: display organizationInformation on BrokerUI connectors page

- src/app/component-library/catalog/asset-detail-dialog/markdown-description/markdown-description.component.ts
- src/app/component-library/catalog/view-selection/view-mode-enum.ts
- src/app/component-library/catalog/view-selection/view-mode-item.ts
- src/app/component-library/catalog/view-selection/view-selection.component.html
- src/app/component-library/catalog/view-selection/view-selection.component.ts
- src/app/core/utils/local-storage-utils.ts
- src/app/core/utils/local-stored-value.ts
- src/app/core/utils/type-utils.ts
- src/app/routes/broker-ui/catalog-page/catalog-page/catalog-page.component.ts
- fix hover on view mode select
- fix local storage values (to string)
- harden local storage interaction
- fix asset description not updating correctly after edit
> fix: asset description height after edit, some styling

- CHANGELOG.md
- docker/default.conf.template
> fix: auth proxy issues

- CHANGELOG.md
- package-lock.json
- src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
> chore: prepare release

- CHANGELOG.md
- src/app/routes/connector-ui/contract-definition-page/asset-select/asset-select.component.html
closes https://github.com/sovity/edc-ui/issues/684
> fix: asset select issues from bad compare function

- CHANGELOG.md
- src/app/core/services/http-params-mapper.service.ts
- src/app/core/validators/valid-query-param.ts
- src/app/core/validators/validation-messages.ts
- src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
- src/app/routes/connector-ui/asset-page/asset-edit-dialog/form/asset-datasource-form-builder.ts
> fix: double encoding of datasource query params

- CHANGELOG.md
- src/app/core/services/api/fake-backend/broker-fake-impl/catalog-fake-impl.ts
- src/app/routes/broker-ui/catalog-page/catalog-page/catalog-page.component.ts
- src/app/routes/broker-ui/catalog-page/state/catalog-page-actions.ts
- src/app/routes/broker-ui/catalog-page/state/catalog-page-state.ts
Contributes to [#44](https://github.com/sovity/authority-portal/issues/44)
```[tasklist]
```
> Replace "connectorEndpoint" with "mdsId" QueryParam

- .env.local-dev
- CHANGELOG.md
- src/app/core/config/app-config-properties.ts
- src/app/core/config/app-config.builder.ts
- src/app/core/config/app-config.ts
- src/app/routes/connector-ui/dashboard-page/dashboard-page/dashboard-page.component.html
Closes https://github.com/sovity/PMO-Software/issues/606
```[tasklist]
```
> Display custom Management API URL for the user

- src/app/core/services/http-params-mapper.service.ts
- src/app/core/services/models/data-address-properties.ts
> fix: add mediaType to transfer requests with http proxy

- CHANGELOG.md
- src/app/routes/broker-ui/catalog-page/broker-data-offer-list/broker-data-offer-list.component.html
- src/app/routes/broker-ui/catalog-page/broker-data-offer-list/broker-data-offer-list.component.scss
- src/app/routes/broker-ui/catalog-page/broker-data-offer-list/broker-data-offer-list.component.ts
closes #722 
```[tasklist]
```
> Fix naming of "Name" column

- CHANGELOG.md
> docs: prepare release

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/component-library/catalog/asset-detail-dialog/asset-property-grid-group-builder.ts
- src/app/core/services/api/fake-backend/connector-fake-impl/asset-fake-service.ts
- src/app/core/services/api/fake-backend/connector-fake-impl/data/test-assets.ts
- src/app/core/services/asset-create-request-builder.ts
- src/app/routes/connector-ui/asset-page/asset-edit-dialog/form/asset-edit-dialog-form-mapper.ts
> fix: nutsLocations field, prepare release

- CHANGELOG.md
- src/app/component-library/initiate-transfer-confirm-tos-dialog/initiate-transfer-confirm-tos-dialog.module.ts
- src/app/component-library/initiate-transfer-confirm-tos-dialog/initiate-transfer-confirm-tos-dialog/initiate-transfer-confirm-tos-dialog.component.html
- src/app/component-library/initiate-transfer-confirm-tos-dialog/initiate-transfer-confirm-tos-dialog/initiate-transfer-confirm-tos-dialog.component.ts
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-page.module.ts
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.ts
closes #1007 [[Prio 6 - Add checkbox to explicitly comply with meta-information] Implementation + Testing](https://github.com/sovity/PMO-Software/issues/1007) 
```[tasklist]
```
> Add Terms of data offer Confirmation

- src/app/component-library/edit-asset-form/edit-asset-form-input/edit-asset-form-input.component.html
- src/app/component-library/edit-asset-form/edit-asset-form-input/edit-asset-form-input.component.ts
- src/app/component-library/edit-asset-form/edit-asset-form-textarea/edit-asset-form-textarea.component.html
- src/app/component-library/edit-asset-form/edit-asset-form-textarea/edit-asset-form-textarea.component.ts
- src/app/component-library/edit-asset-form/edit-asset-form.module.ts
- src/app/component-library/edit-asset-form/edit-asset-form/edit-asset-form.component.html
- src/app/component-library/property-grid/property-grid/property-grid.component.html
- src/app/core/validators/url-validator.ts
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.html
closes sovity/PMO-Software#1370
```[tasklist]
```
> chore: DRY data offer form

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/core/services/api/edc-api.service.ts
- src/app/core/services/api/fake-backend/edc-fake-backend.ts
https://github.com/sovity/PMO-Software/issues/1350
```[tasklist]
```
> feat: fetch a single contract agreement

- CHANGELOG.md
- src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
closes #760 [MDS Variant] Add description for fields in Asset Creation Mask
Sources used: 
Zammad
[MDS Ontology](https://github.com/Mobility-Data-Space/mobility-data-space/wiki/MDS-Ontology)
[MDS Asset Attributes](https://github.com/Mobility-Data-Space/mobility-data-space/wiki/MDS-Asset-Attributes)
```[tasklist]
```
> MDS Variant: add description for fields in asset creation mask 

- CHANGELOG.md
- src/app/core/services/api/fake-backend/connector-fake-impl/asset-fake-service.ts
- src/app/core/services/api/fake-backend/connector-fake-impl/data/test-assets.ts
- src/app/core/services/asset-builder.ts
- src/app/routes/connector-ui/asset-edit-page/asset-edit-page/asset-edit-page.component.ts
closes #1023
```[tasklist]
```
> Handle custom properties during asset update

- CHANGELOG.md
https://github.com/sovity/edc-ui/issues/798
```[tasklist]
```
> chore: Release preparation

- src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
- src/app/routes/connector-ui/asset-page/keyword-select/keyword-select.component.html
wording changes to sync with the #1430
```[tasklist]
```
> Small UI wording fixes

- CHANGELOG.md
https://github.com/sovity/edc-ui/issues/812
```[tasklist]
```
> chore: Release preparation 4.1.3

- docker/Dockerfile
Updates the base-image.
```[tasklist]
```
> chore(docker): update base image

- CHANGELOG.md
- src/app/component-library/policy-editor/editor/expression-form-controls.ts
- src/app/component-library/policy-editor/editor/recipes/timespan-restriction-dialog/timespan-restriction-expression.ts
- src/app/component-library/policy-editor/model/policy-form-adapter.ts
- src/app/component-library/policy-editor/model/policy-mapper.ts
- src/app/core/adapters/custom-date-adapter.ts
- src/app/core/services/api/fake-backend/connector-fake-impl/data/test-policies.ts
- src/app/core/utils/date-utils.ts
closes https://github.com/sovity/edc-ui/issues/815
> fix: time restriction upper bound conversion issues

- CHANGELOG.md
https://github.com/sovity/edc-ui/issues/833
```[tasklist]
```
> chore: Release prep v4.1.4

- src/app/core/services/api/fake-backend/connector-fake-impl/data-offer-fake-service.ts
- src/app/routes/connector-ui/asset-edit-page/asset-edit-page/asset-edit-page.component.ts
> chore: small fixes

- CHANGELOG.md
https://github.com/sovity/edc-ui/issues/852
```[tasklist]
```
> chore: Release prep 4.1.5

- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog-form.ts
- src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.html
closes #739 No Default Custom Method.
```[tasklist]
```
> Mandatory custom method

- CHANGELOG.md
https://github.com/sovity/edc-ui/issues/865
```[tasklist]
```
> chore: Release 4.1.6

- CHANGELOG.md
Closes: #872 
```[tasklist]
```
> release: v4.1.7

- src/app/routes/connector-ui/asset-list-page/asset-create-dialog/asset-create-dialog.component.html
> Remove duplicate labels from create asset dialog
