sovity/edc-ui

src/modules/edc-demo/components/policy-view/policy-view.component.ts, src/modules/edc-dmgmt-client/model/policyDefinition.ts
This is an attempt to fix an issue with the deletion confirmation dialog in policy definitions page.
By checking the same dialog where the bug was happening.
- fixes # ([issue](https://github.com/sovity/edc-ui/issues/43))
=> fix: show policy definition id in deletion dialog

package-lock.json
- closes #48 
- Updated dependencies via "npm update" to close dependabot PRs
- Running "npm update" also updated the  lockfile version from 2 to 3.
- Version 3 file size is smaller.
- Requires NPM Version ^7.
- See https://docs.npmjs.com/cli/v8/using-npm/config#lockfile-version
- Our recommended Nodejs Version is 16 gallium which contains NPM Version 8.
=> chore "npm update"

src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts, src/modules/edc-demo/services/policy-definition-builder.ts, src/modules/edc-dmgmt-client/api/contractAgreement.service.ts
Initiating transfer processes is faulty due to backend expecting data from contract definitions which aren't present in contract agreements causing us to write our own extension to fix this issue short-term.
=> fix transfer process initiation not working

.github/workflows/automerge.yml
Unfortunately it is not possible to mark a failing job as green. 
https://github.com/actions/runner/issues/2347
=> chore: add continue on error if couldn't automerge

CHANGELOG.md, src/modules/edc-demo/components/catalog-browser/catalog-browser.component.html, src/modules/edc-demo/components/new-policy-dialog/new-policy-dialog.component.html
Placeholder URLs were missing "/catalog/" path.
-   [x] I have **formatted the title** correctly and precisely
-   [x] My code follows the **style guidelines** of this project
-   [x] I have performed a **self-review** of my own code
-   [x] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [x] I have made corresponding changes to the **documentation**
-   [x] My changes generate **no new warnings** (performed checkstyle check locally)
-   [ ] I have added **tests that prove my fix** is effective or that my feature works
-   [x] New and existing unit **tests pass locally** with my changes
-   [x] Any dependent **changes have been merged** and published in downstream modules
-   [x] I have added/updated **copyright headers**
=> fix: Placeholder URLs missing "/catalog/" path

src/modules/edc-demo/components/keyword-select/keyword-select.component.html, src/modules/edc-demo/components/keyword-select/keyword-select.component.ts
- closes #118 
- keyword select now adds text as tag on blur
- keyword select now splits pasted text with separators by separators
- added semicolon separator, although it won't instantly split tags due to "keycode" limitation on german keyboards where the semicolon is two keystrokes "Shift + Comma" and Angular Material API expecting semicolons. When blurring or pressing enter, keywords will be split by semicolon either way.
=> fix keyword select not adding value on blur

CHANGELOG.md, src/modules/app/components/navigation/navigation.component.html
Fixed closing of side nav-bar on pressing escape
With mock backend
=> fix: closing navbar on pressing escape button

CHANGELOG.md, src/modules/edc-demo/components/catalog-browser-fetch-detail-dialog/catalog-browser-fetch-detail-dialog.component.html
Updated icon for fetch details option in the Catalog browser 
With mock backend
=> fix: better catalog fetch details icon

CHANGELOG.md, fake-backend/json/policyDefinitions.json, src/modules/edc-demo/components/dashboard/dashboard.component.html
- fix dashboard contract definitions being called "data offers"
=> fix dashboard data offers not called contract definitions

CHANGELOG.md, src/modules/app/app.module.ts, src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts, src/modules/edc-demo/components/logout/location-history-utils.ts, src/modules/edc-demo/components/logout/logout.component.ts, src/modules/edc-demo/components/logout/previous-route-listener.ts, src/modules/edc-demo/utils/form-group-utils.ts
This is not a full fix as it will leave two entries in the history of the last visited page. The exact solution would be to remove the leak of the list of routes being re-used for the list of navigation menu entries.
closes https://github.com/sovity/PMO-Software/issues/144
=> 2023 04 12 logout history

package-lock.json, package.json
@sovity.de/edc-client now uses a different version schema
=> fix edc-client version

CHANGELOG.md, src/app/component-library/json-dialog/json-dialog/json-dialog.component.html
Renamed button from cancel to close in json-dialogs
With Fake Backend
-   [x] blocked by #https://github.com/sovity/edc-ui/issues/285
-   [ ] I have **formatted the title** correctly and precisely
-   [x] My code follows the **style guidelines** of this project
-   [x] I have performed a **self-review** of my own code
-   [ ] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [ ] I have made corresponding changes to the **documentation**
-   [x] My changes generate **no new warnings** (performed checkstyle check locally)
-   [ ] I have added **tests that prove my fix** is effective or that my feature works
-   [ ] New and existing unit **tests pass locally** with my changes
-   [ ] Any dependent **changes have been merged** and published …
=> feat: Renamed button from cancel to close in json-dialogs

docker/99-generate-app-config.sh, docker/Dockerfile, docker/default.conf.template
Configure container image to run as a non-root user. Based on, supersedes, and closes #370.
Local build and manual test.
-   [x] I have **formatted the title** correctly and precisely
-   [x] My code follows the **style guidelines** of this project
-   [x] I have performed a **self-review** of my own code
-   [x] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [ ] I have made corresponding changes to the **documentation**
-   [ ] My changes generate **no new warnings** (performed checkstyle check locally)
-   [ ] I have added **tests that prove my fix** is effective or that my feature works
-   [ ] New and existing unit **tests pass locally** with my changes
-   [ ] Any dependent **changes have been merged** and published in downstream …
=> Non-root container image

src/app/component-library/catalog/asset-detail-dialog/asset-property-grid-group-builder.ts, src/app/core/services/api/contract-offer.service.ts, src/app/core/services/asset-properties.ts, src/app/core/services/asset-property-mapper.ts, src/app/core/services/asset-service-mapped.ts, src/app/routes/broker-ui/catalog-page/catalog-page/mapping/broker-catalog-mapper.ts, src/app/routes/connector-ui/asset-page/asset-page/asset-page.component.ts, src/app/routes/connector-ui/contract-agreement-page/contract-agreement-cards/contract-agreement-card-mapped.service.ts, src/app/routes/connector-ui/contract-definition-page/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts, src/app/routes/connector-ui/transfer-history-page/transfer-history-page/transfer-history-page.component.html, src/app/routes/connector-ui/transfer-history-page/transfer-history-page/transfer-history-page.component.ts
- fix custom transfer json transfer initiations missing the connector endpoint
- removed support for the legacy asset property "originator", which is not guaranteed to be set and was a workaround for MS7 EDCs which will be removed for EDC 0 either way.
- fixes https://github.com/sovity/edc-ui/discussions/454
=> Fix custom transfer json missing connector endpoint

package-lock.json, package.json, src/app/component-library/catalog/asset-detail-dialog/asset-detail-dialog-data.service.ts, src/app/core/services/api/fake-backend/asset-fake-service.ts, src/app/core/services/api/fake-backend/contract-agreement-fake-service.ts, src/app/core/services/api/fake-backend/data/test-assets.ts, src/app/core/services/api/fake-backend/data/test-policies.ts, src/app/core/services/api/fake-backend/edc-fake-backend.ts, src/app/core/services/api/fake-backend/policy-definition-fake-service.ts, src/app/core/services/api/fake-backend/transfer-history-fake-service.ts, src/app/core/utils/object-utils.ts
also fixes a risk where we did not map between the generated classes and the json.
mapping should be done to not let the javascript json serializer automatically serialize dates or put string values into dates
=> fix: contract agreement page and transfer history page fake backend

src/app/routes/connector-ui/asset-page/asset-create-dialog/asset-create-dialog.component.html, src/app/routes/connector-ui/contract-agreement-page/contract-agreement-transfer-dialog/contract-agreement-transfer-dialog.component.html
This PR fixes consistency of buttons styles in "Create New Asset" and "Contract Agreement" dialogs in both themes.
mat-stroked-button was changed to mat-button as it was before but with "accent" colod
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
-   Test A
-   Test B
-   ...
**Test Configuration**:
-   Firmware version:
-   Hardware:
-   Toolchain:
-   SDK:
_Use keywords to automate: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword_
-   fixes # (issue)
-   closes # (issue)
-   ...
-   [ ] blocked by # (issue)
-   [ ] I have **formatted the title** correctly and …
=> chore: change material buttons type

CHANGELOG.md, src/app/routes/connector-ui/connector-ui.module.ts, src/app/routes/connector-ui/logout-page/location-history-utils.ts
Solves NullInjectionError of PreviousRouteListener and ensures a working`/logout` page.
Set `EDC_UI_ACTIVE_PROFILE=sovity-hosted-by-sovity` and click on the Logout button.
closes #591
=> fix: broken /logout page

CHANGELOG.md, src/app/core/services/api/fake-backend/broker-fake-impl/catalog-fake-impl.ts, src/app/core/utils/array-utils.ts, src/app/routes/broker-ui/catalog-page/catalog-page/catalog-page.component.ts, src/app/routes/broker-ui/catalog-page/state/catalog-page-actions.ts, src/app/routes/broker-ui/catalog-page/state/catalog-page-state.ts
closes sovity/authority-portal#841
```[tasklist]
```
=> feat: broker can initialize connector endpoint filters from query params

CHANGELOG.md, src/app/routes/broker-ui/catalog-page/catalog-page/catalog-page.component.ts, src/app/routes/broker-ui/catalog-page/state/catalog-page-actions.ts, src/app/routes/broker-ui/catalog-page/state/catalog-page-state.ts
=> chore: prepare release

CHANGELOG.md, src/app/core/services/models/data-address-properties.ts
This resolves #702 by not prefixing headers for the HTTP data transfer with the EDC namespace as the EDC expects them without, see https://github.com/eclipse-edc/Connector/blob/5803513f0c4cc795c0d1d069f7039c8ca1bd8f7e/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java#L131.
```[tasklist]
```
=> HTTP Data Transfer: Remove EDC prefix for headers in data address property

CHANGELOG.md, src/app/component-library/catalog/asset-detail-dialog/asset-detail-dialog.component.html, src/app/component-library/catalog/asset-detail-dialog/asset-detail-dialog.component.ts, src/app/component-library/catalog/contract-offer-icon/contract-offer-icon.component.ts, src/app/core/services/api/fake-backend/connector-fake-impl/catalog-fake-service.ts, src/app/core/services/api/fake-backend/connector-fake-impl/contract-agreement-fake-service.ts, src/app/core/services/api/fake-backend/connector-fake-impl/data/test-assets.ts, src/app/core/services/api/fake-backend/connector-fake-impl/ee-fake-service.ts, src/app/core/services/api/fake-backend/edc-fake-backend.ts, src/app/core/services/mailto-link-builder.spec.ts, src/app/core/services/mailto-link-builder.ts, src/app/core/utils/record-utils.ts
=> feat: specific data offer UI for on request asset

CHANGELOG.md, src/app/component-library/policy-editor/model/policy-verbs.ts
closes #1410 Policy Creation section shows wrong date format
Single Date
Date Timespan
```[tasklist]
```
=> Fix date format in Policy Expression mat-hint

CHANGELOG.md, src/app/component-library/edit-asset-form/edit-asset-form-input/edit-asset-form-input.component.html, src/app/component-library/edit-asset-form/edit-asset-form-input/edit-asset-form-input.component.ts, src/app/component-library/edit-asset-form/edit-asset-form/edit-asset-form.component.html, src/app/component-library/edit-asset-form/keyword-select/keyword-select.component.html, src/app/component-library/edit-asset-form/language-select/language-select.component.html, src/app/component-library/edit-asset-form/language-select/language-select.component.ts, src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
closes #1439 Implement Tooltips on Create Date Offer tab
closes #811 Create data offer: no info icons & suggestion-text not accurate
**Tooltip**: "The main name of your asset. It will also be the name of the data offering displayed in the catalog."
**Tooltip**: "Asset ID, used internally, is an auto-generated string in a URL-compatible format, combining the asset name and version with a urn:artifact: prefix. You can customize it if needed."
**Tooltip**: "Keywords make the data offer easier to find. They appear as tags on "Assets" and "Catalog Browser" pages."
**Tooltip**: "The version of your asset. Especially useful if you have iterations of the same asset."
**Renamed** to "Language of the content" 
Without **"Advanced Fields"**
**No changes**
**No …
=> Add tooltips and hints to the Create Data Offer page

CHANGELOG.md, src/app/component-library/catalog/contract-offer-mini-list/contract-offer-mini-list.component.html, src/app/component-library/catalog/contract-offer-mini-list/contract-offer-mini-list.component.ts
#795 Contract offer ID is missing on catalog browser view page
Before
After
```[tasklist]
```
=> feat: Add Contract Offer Id Element back to the Catalog Browser Detail Dialog

CHANGELOG.md, src/app/component-library/edit-asset-form/edit-asset-form/edit-asset-form.component.html, src/app/routes/connector-ui/asset-page/asset-edit-dialog/asset-edit-dialog.component.html
closes #800 Attribute names are inconsistent on asset creation (EDC UI) vs the data catalog page (AP)
Only cosmetic (no form control name) changes in this PR to avoid compat issues and BE refactoring
```[tasklist]
```
=> chore: rename Name to Title

CHANGELOG.md, docker/Dockerfile, docker/default.conf.template, src/app/core/config/app-config-initializer.ts
This PR fixes a caching issue wherein the app-config.json was aggressively cached and always loaded from disk cache without validation which caused new deployments on the same URL to use an outdated configuration.
See https://github.com/sovity/authority-portal/pull/325 for more information
```[tasklist]
```
=> fix: invalid configuration after version upgrade

CHANGELOG.md, src/app/shared/business/policy-editor/model/policy-form-adapter.ts
closes #846
Explanation:
```
day start |        | day end
GEQ       |        |
LT        |        |
|        | GT (+1 day)
|        | LEQ (+1 day)
```
=> fix: date to datetime conversion with operators LT and GT

CHANGELOG.md, src/app/routes/connector-ui/dashboard-page/dashboard-page/dashboard-page.component.html, src/assets/i18n/en.json
#831 Inconsistent renaming "Contract Definition" to "Data Offer"
```[tasklist]
```
=> fix: data offer renaming

src/app/core/services/api/fake-backend/connector-fake-impl/data-offer-fake-service.ts, src/app/shared/business/edit-asset-form/form/edit-asset-form-validators.ts
if the always-true policy was removed, BE creates a new always-true policy
So the old check if always-true policy doesn't exist isn't necessary anymore
But the old checks work as intended
```[tasklist]
```
=> Fix edit asset form validator

.github/ISSUE_TEMPLATE/release.md, .github/PULL_REQUEST_TEMPLATE.md, docs/dev/changelog_updates.md
=> chore: update Releasing procedure: check issue links

src/app/shared/business/edit-asset-form/edit-asset-form.component.html
#870 Wrong label for Description field on asset creation dialog
```[tasklist]
```
=> fix description label

CHANGELOG.md, src/app/core/services/nav-items-builder.ts
closes #836 Sidebar with inconsistent separation in Providing and Consuming sections
**before:**
**after:**
```[tasklist]
```
=> feat: rearrange sidebar
